# -*- coding: utf-8 -*-
"""Attendance Generated.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kg3BBDwRkUrUEseOmAKtipzLuGlPjfmS
"""
import sys

import pandas as pd
import re


### List should be TEAM Genereted"""
def read_file(filename="list_.csv",sessionName="Session 1"):
    df=pd.read_csv(filename,encoding = "utf-8")
    listOfStudents=df['Full Name']
    setOfStudents=set(listOfStudents)
    #setOfStudents
    df_allSections=pd.read_excel('PIT List All Sections.xlsx')
    #len(setOfStudents)
    #Change session name here
    #Mark everybody absent
    df_allSections[sessionName]='A'
    return df_allSections,listOfStudents
#Cleaning data from teams generated excel file
def removingParantheis(listOfText):
    import re
    return [re.sub(r'[^\w\s]', '', x) for x in listOfText]
def removingGuestFromText(listOfText):
    return [x.replace("Guest","") for x in listOfText]

def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

def get_details(student_list_clean):
    roll_numbers = []
    names = []
    for i in student_list_clean:
        name = []
        for j in i.split():
            if hasNumbers(j):
                j = j.lower()
                j = re.sub("[^0-9]", "", j)
                roll_numbers.append(j)
            else:
                name.append(j)
        names.append(' '.join(name))
    return names,roll_numbers

 #Marking Attendance
 #Making a copy just in case
def mark_attendance(df_allSections,names,roll_numbers):
    #df_temp = df_allSections.copy()
    for name in names:
      df_allSections.loc[df_allSections["Name"].str.strip() == name.strip(),"Session 1"] = "P"
    for rollNo in roll_numbers:
      df_allSections.loc[df_allSections["RollNo"].str.strip() == rollNo.strip(),"Session 1" ] = "P"
    #Attendance
    #Present number of students
    present_count  = df_allSections.loc[df_allSections["Session 1"] == "P","Session 1"].count()
    return df_allSections,present_count
import sys
def main():
    try:
        filename = sys.argv[1]
        df_allSections, listOfStudents = read_file()
        student_list_clean = removingParantheis(list(set(listOfStudents)))
        student_list_clean = removingGuestFromText(student_list_clean)
        names, roll_numbers = get_details(student_list_clean)
        df_allSections, present_count = mark_attendance(df_allSections, names, roll_numbers)
        print("Present Students: ", present_count)
        # Save to csv
        df_allSections.to_csv('Attendance Seminar.csv', index=False)
    except:
        print("Enter teams attendance file name as: attendance_marker.py <filename>")
        print("Run the script again")
